# Load the required libraries
library(ggtree)
library(ggplot2)
library(ggmsa)

# /Users/pimswart/mafft_output_P_all_pharokka_of_representatives_manualremovedbacterial_fasta_catted
# /Users/pimswart/mafft_output_P_all_separate_representatives_fa_catted
nt_sequences <- "/Users/pimswart/mafft_output_P_all_separate_representatives_fa_catted"
#ggmsa(nt_sequences, 35500, 35550, color = "Chemistry_AA", font = "DroidSansMono", char_width = 0.5, seq_name = FALSE)

# Read the tree file generated by IQ-TREE
# /Users/pimswart/mafft_output_P_all_pharokka_of_representatives_manualremovedbacterial_fasta_catted.treefile
# /Users/pimswart/copy_mafft_output_P_all_separate_representatives_fa_catted.treefile
tree <- read.tree("/Users/pimswart/mafft_output_P_all_separate_representatives_fa_catted.treefile")

# Create a data frame with tip labels and the corresponding propagation numbers
tip_data <- data.frame(
  tip_label = tree$tip.label,
  propagation_number = gsub("^P(\\d+)\\..*$", "\\1", tree$tip.label))

# Convert the propagation_number column to a factor with proper levels
tip_data$propagation_number <- factor(tip_data$propagation_number, levels = 1:10)

# Define the desired color palette
color_palette <- c("#000041", "#0000A9", "#0049FF", "#00A4DE", "#03E070", "#5DFC21", "#F6F905", "#FFD701", "#FF9500", "#FF3300")

# Plot the tree with colored tip points based on the propagation numbers
p1 <- ggtree(tree) %<+% tip_data +
  geom_tippoint(aes(color = propagation_number)) +
  scale_color_manual(values = color_palette) +  # Set the color palette
  #geom_treescale(x = 0, y = 45, fontsize = 4, linesize = 2, width = 10) +
  geom_tiplab(size = 1) +
  theme(legend.position = "none")  # Remove the legend
plot(p1)

# Custom set of colors using the Clustal color scheme
custom_colors <- c("#F6F5F4", "#64F73F", "#FFB340", "#EB413C", "#3C88EE")

msaplott <- msaplot(p=p1,
                    fasta="/Users/pimswart/mafft_output_P_all_separate_representatives_fa_catted", 
                    #window=c(1, 10000),
                    offset=1.5,
                    color = custom_colors,
                    width = 2
)
msaplott
# Save the plot as a PDF file
ggsave("/Users/pimswart/your_plotttttttt.pdf", plot = msaplott, device = "pdf", width = 10, height = 10)
ggsave("/Users/pimswart/your_plottttttttt.png", plot = msaplott, width = 10, height = 10)



